import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { montserrat } from "@/lib/fonts";
import Navbar from "@/components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${montserrat.className} antialiased overflow-x-hidden`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
